import os

from constants import GPU_H100, GPU_L4, HOURS_6, MAX_CONTAINERS, MINUTES_1, MINUTES_10, MINUTES_15, MINUTES_30

BOLTZ2_GPU = os.environ.get("BOLTZ2_GPU", GPU_H100)
BOLTZ2_TIMEOUT = int(os.environ.get("BOLTZ2_TIMEOUT", MINUTES_30))
BOLTZ2_MAX_CONTAINERS = int(os.environ.get("BOLTZ2_MAX_CONTAINERS", MAX_CONTAINERS))
BOLTZ2_SCALEDOWN_WINDOW = int(os.environ.get("BOLTZ2_SCALEDOWN_WINDOW", MINUTES_1))

ESMC_GPU = os.environ.get("ESMC_GPU", GPU_L4)
ESMC_TIMEOUT = int(os.environ.get("ESMC_TIMEOUT", MINUTES_10))
ESMC_MAX_CONTAINERS = int(os.environ.get("ESMC_MAX_CONTAINERS", MAX_CONTAINERS))
ESMC_SCALEDOWN_WINDOW = int(os.environ.get("ESMC_SCALEDOWN_WINDOW", MINUTES_1))

ESMFOLD2_GPU = os.environ.get("ESMFOLD2_GPU", GPU_H100)
ESMFOLD2_TIMEOUT = int(os.environ.get("ESMFOLD2_TIMEOUT", MINUTES_30))
ESMFOLD2_MAX_CONTAINERS = int(os.environ.get("ESMFOLD2_MAX_CONTAINERS", MAX_CONTAINERS))
ESMFOLD2_SCALEDOWN_WINDOW = int(os.environ.get("ESMFOLD2_SCALEDOWN_WINDOW", MINUTES_1))

ESM3_GPU = os.environ.get("ESM3_GPU", GPU_H100)
ESM3_TIMEOUT = int(os.environ.get("ESM3_TIMEOUT", MINUTES_15))
ESM3_MAX_CONTAINERS = int(os.environ.get("ESM3_MAX_CONTAINERS", MAX_CONTAINERS))
ESM3_SCALEDOWN_WINDOW = int(os.environ.get("ESM3_SCALEDOWN_WINDOW", MINUTES_1))

BOLTZGEN_GPU = os.environ.get("BOLTZGEN_GPU", GPU_H100)
BOLTZGEN_TIMEOUT = int(os.environ.get("BOLTZGEN_TIMEOUT", MINUTES_30))
BOLTZGEN_MAX_CONTAINERS = int(os.environ.get("BOLTZGEN_MAX_CONTAINERS", MAX_CONTAINERS))
BOLTZGEN_SCALEDOWN_WINDOW = int(os.environ.get("BOLTZGEN_SCALEDOWN_WINDOW", MINUTES_1))

PROTEINMPNN_GPU = os.environ.get("PROTEINMPNN_GPU", GPU_L4)
PROTEINMPNN_TIMEOUT = int(os.environ.get("PROTEINMPNN_TIMEOUT", MINUTES_10))
PROTEINMPNN_MAX_CONTAINERS = int(os.environ.get("PROTEINMPNN_MAX_CONTAINERS", MAX_CONTAINERS))
PROTEINMPNN_SCALEDOWN_WINDOW = int(os.environ.get("PROTEINMPNN_SCALEDOWN_WINDOW", MINUTES_1))

LIGANDMPNN_GPU = os.environ.get("LIGANDMPNN_GPU", GPU_L4)
LIGANDMPNN_TIMEOUT = int(os.environ.get("LIGANDMPNN_TIMEOUT", MINUTES_10))
LIGANDMPNN_MAX_CONTAINERS = int(os.environ.get("LIGANDMPNN_MAX_CONTAINERS", MAX_CONTAINERS))
LIGANDMPNN_SCALEDOWN_WINDOW = int(os.environ.get("LIGANDMPNN_SCALEDOWN_WINDOW", MINUTES_1))

SOLUBLEMPNN_GPU = os.environ.get("SOLUBLEMPNN_GPU", GPU_L4)
SOLUBLEMPNN_TIMEOUT = int(os.environ.get("SOLUBLEMPNN_TIMEOUT", MINUTES_10))
SOLUBLEMPNN_MAX_CONTAINERS = int(os.environ.get("SOLUBLEMPNN_MAX_CONTAINERS", MAX_CONTAINERS))
SOLUBLEMPNN_SCALEDOWN_WINDOW = int(os.environ.get("SOLUBLEMPNN_SCALEDOWN_WINDOW", MINUTES_1))

BINDCRAFT_GPU = os.environ.get("BINDCRAFT_GPU", GPU_H100)
BINDCRAFT_TIMEOUT = int(os.environ.get("BINDCRAFT_TIMEOUT", HOURS_6))
BINDCRAFT_MAX_CONTAINERS = int(os.environ.get("BINDCRAFT_MAX_CONTAINERS", MAX_CONTAINERS))
BINDCRAFT_SCALEDOWN_WINDOW = int(os.environ.get("BINDCRAFT_SCALEDOWN_WINDOW", MINUTES_1))
